[package]
name = "smplc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smplc_lexer = { workspace = true }
smplc_ast = { workspace = true }
smplc_parse = { workspace = true }
smplc_semcheck = { workspace = true }
smplc_typecheck = { workspace = true }
smplc_translate = { workspace = true }
comet_backend_x86 = { workspace = true }

clap = { version = "4.2.5", features = ["derive"] }
colored = "2.0.0"
