[workspace]
members = [
    "frontend/smplc_parse",
    "frontend/smplc_lexer",
    "frontend/smplc_ast",

    "semantic/smplc_hir",
    "semantic/smplc_semcheck",

    "linear/smplc_ir",
    "linear/smplc_translate",

    "backend",

    "utils/smplc_macros",

    "bin",
]
