[workspace]
members = [
    "frontend/smplc_parse",
    "frontend/smplc_lexer",
    "frontend/smplc_ast",

    "middleend",
    "linear/smplc_ir",

    "backend",
    "bin",

    "utils/smplc_macros",
]
