[package]
name = "smplc_translate"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
parse_int = "0.6.0"
nalgebra = "0.33.2"

comet_ir = { workspace = true }

smplc_thir = { path = "../typing/smplc_thir" }
