[package]
name = "middleend"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"

smplc_ast = { path = "../frontend/smplc_ast" }
smplc_ir = { path = "../linear/smplc_ir" }
