[package]
name = "smplc_translate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smplc_hir = { path = "../../semantic/smplc_hir" }
smplc_ir = { path = "../smplc_ir" }
